services:
  - type: web
    name: sistema-pdf
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: gunicorn config.wsgi:application --workers=2 --bind 0.0.0.0:$PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_prod
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-pdf-db
          property: connectionString
databases:
  - name: sistema-pdf-db
    plan: free
