# Generated by Django 5.2.6 on 2025-10-20 11:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], help_text='Tipo: Receita ou Despesa', max_length=20)),
                ('descricao', models.CharField(help_text='Descrição da classificação', max_length=100)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a classificação está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'db_table': 'classificacao',
            },
        ),
        migrations.CreateModel(
            name='MovimentoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGAR', 'Conta a Pagar'), ('RECEBER', 'Conta a Receber')], help_text='Tipo do movimento', max_length=10)),
                ('descricao', models.TextField(help_text='Descrição do movimento')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do movimento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade_parcelas', models.IntegerField(default=1, help_text='Número de parcelas')),
                ('data_emissao', models.DateField(help_text='Data de emissão')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='ABERTO', help_text='Status do movimento', max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o movimento está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimento de Conta',
                'verbose_name_plural': 'Movimentos de Contas',
                'db_table': 'movimentocontas',
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor'), ('FATURADO', 'Faturado')], help_text='Tipo da pessoa: Cliente, Fornecedor ou Faturado', max_length=20)),
                ('razao_social', models.CharField(help_text='Razão social ou nome completo', max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome fantasia (opcional)', max_length=200, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, help_text='CNPJ ou CPF', max_length=20, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o cadastro está ativo ou inativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='MovimentoClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_classificado', models.DecimalField(decimal_places=2, help_text='Valor classificado', max_digits=10)),
                ('classificacao', models.ForeignKey(help_text='Classificação relacionada', on_delete=django.db.models.deletion.PROTECT, to='core.classificacao')),
                ('movimento', models.ForeignKey(help_text='Movimento relacionado', on_delete=django.db.models.deletion.CASCADE, to='core.movimentocontas')),
            ],
            options={
                'verbose_name': 'Classificação do Movimento',
                'verbose_name_plural': 'Classificações dos Movimentos',
                'db_table': 'movimento_classificacao',
            },
        ),
        migrations.CreateModel(
            name='ParcelaContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(help_text='Número da parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, help_text='Valor da parcela', max_digits=10)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento da parcela')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data de pagamento (se pago)', null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago')], default='ABERTO', help_text='Status da parcela', max_length=20)),
                ('identificacao_unica', models.CharField(help_text='Identificação única da parcela', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movimento', models.ForeignKey(help_text='Movimento relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.movimentocontas')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'db_table': 'parcelacontas',
                'ordering': ['numero_parcela'],
            },
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='pessoa',
            field=models.ForeignKey(help_text='Pessoa relacionada ao movimento', on_delete=django.db.models.deletion.PROTECT, to='core.pessoas'),
        ),
    ]
